- hosts: server
  tasks:
    - name: copy file test1.txt test2.txt test3.txt test4.txt
      copy:
        src: "{{ item }}"
        dest: /tmp
      loop:
      - test1.txt
      - test2.txt
      - test3.txt
      - test4.txt
